#!/bin/sh -xv
# system one time tasks

PATH=/sbin:/bin:/usr/sbin:/usr/bin

RUNLEVEL=S /sbin/rc sysinit
RUNLEVEL=S /sbin/rc boot

touch /run/runit/{stopit,reboot}
chmod 0 /run/runit/{stopit,reboot}

# vim:filetype=sh tabstop=3 shiftwidth=3 expandtab
