#!/bin/sh -xv
exec 2>&1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

sync && sync && sync

echo 'Waiting for services to stop...'
#----------------------------------------------------------------
# notes on process management

# very interesting article
#   http://mywiki.wooledge.org/ProcessManagement

# from http://partmaps.org/era/unix/award.html#kill
# Useless Use of Kill -9 form letter
#    No no no.  Don't use kill -9.
#    It doesn't give the process a chance to cleanly:
#    1) shut down socket connections
#    2) clean up temp files
#    3) inform its children that it is going away
#    4) reset its terminal characteristics
#         and so on and so on and so on.
#    Generally, send 15, and wait a second or two, and if that doesn't
#    work, send 2, and if that doesn't work, send 1.  If that doesn't,
#    REMOVE THE BINARY because the program is badly behaved!
#    Don't use kill -9.  Don't bring out the combine harvester just to tidy
#    up the flower pot.
# /bin/kill --table
#  1 HUP      2 INT      3 QUIT     4 ILL      5 TRAP     6 ABRT     7 BUS
#  8 FPE      9 KILL    10 USR1    11 SEGV    12 USR2    13 PIPE    14 ALRM
# 15 TERM    16 STKFLT  17 CHLD    18 CONT    19 STOP    20 TSTP    21 TTIN
# 22 TTOU    23 URG     24 XCPU    25 XFSZ    26 VTALRM  27 PROF    28 WINCH
# 29 POLL    30 PWR     31 SYS

# following the above quidelines
# the below does not work, sv is restarting the service when I send INT or HUP
# # send 15 (TERM), wait a second or two
# sv -w5 term /run/runit/runsvdir/current/*
# # if that doesn't work, send 2 (INT)
# sv -w5 interrupt /run/runit/runsvdir/current/*
# # if that doesn't work, send 1 (HUP)
# sv -w5 hup /run/runit/runsvdir/current/*

# below shutdown sends TERM and CONT to running services
sv -w30 shutdown /run/runit/runsvdir/current/*

# do not send a kill here, /etc/runlevels/shutdown/killprocs
#  sends a TERM to all processes and then sends a KILL to all
#  processes

# echo 'Switching to single...'
# runsvchdir single

echo 'Shutdown...'
test -x /run/runit/reboot && LAST=6    || LAST=0
test -x /run/runit/reboot && RC=reboot || RC=shutdown
RUNLEVEL=$LAST /sbin/rc $RC

# to check out any messages
sleep 5

# vim:filetype=sh tabstop=3 shiftwidth=3 expandtab
