#!/bin/sh -xv
exec 2>&1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

sync && sync && sync

echo 'Waiting for services to stop...'
sv -w30 shutdown /run/runit/runsvdir/current/*
# sleep to show me any service that is not dying and correct it
#  to respond to a TERM or CONT
# sleep 10
# do not send a kill here, /etc/rc.shutdown sends a TERM
#  to all processes and then sends a KILL to all processes
# sv force-shutdown /var/run/runit/runsvdir/current/*

# echo 'Switching to single...'
# runsvchdir single

echo 'Shutdown...'
test -x /run/runit/reboot && LAST=6    || LAST=0
test -x /run/runit/reboot && RC=reboot || RC=shutdown
RUNLEVEL=$LAST /sbin/rc $RC

# to check out any messages
sleep 5

# vim:filetype=sh tabstop=3 shiftwidth=3 expandtab
